spring.application.name=researchAssistant
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=
gemini.api.key = AIzaSyDmnsZ7ku-3STnbvoU8qzZUKqMXSc-YxFY
server.port = 8083

# MySQL DataSource Configuration
spring.datasource.url=spring.datasource.url=jdbc:mysql://localhost:3306/aiResearchAssistant
spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect